name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.GH_PACKAGES_USER }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
        
    - name: Build the Docker image
      run: |
       docker build . --file Dockerfile --tag ghcr.io/julioarruda/sample01:${{ github.sha }}
       docker tag ghcr.io/julioarruda/sample01:${{ github.sha }} ghcr.io/julioarruda/sample01:latest
     
     
    - name: Docker Push
      run: |
       docker push ghcr.io/julioarruda/sample01:${{ github.sha }}
       docker push ghcr.io/julioarruda/sample01:latest

    - name: Set deploystatus in_progress
      uses: unacast/actions-github-deployment-status@0.4.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        status: in_progress

    - name: Set an environment
      run: |
        echo '::set-env name=DEPLOY_ENVIRONMENT::Dev'

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'demoteste01923'
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        images: 'ghcr.io/julioarruda/sample01:${{ github.sha }}'

    - name: Update result to Deployment API
      if: always()
      uses: unacast/actions-github-deployment-status@0.4.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
        description: "Deployed to some magic"
        environment_url: '${{ env.DEPLOY_ENVIRONMENT }}'